config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  mount ActionCable.server => "/cable"

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  resources :feedbacks, only: [:create, :new, :index], path: 'feedback'
  resources :reactions, only: [:create]

  get '/new_chat', to: 'posts#new_chat'
  resources :posts
  resources :bins, path: 'channel'
  resources :bins

  resources :reactions, only: [:index]

  resources :participations, only: :destroy
  resources :rooms, only: [:show, :update], path: 'chat', param: :token
  resources :ratings, only: :create
  devise_for :users#, controllers: { sessions: "users/sessions" }

  root 'static_pages#home'

  get 'banned' => 'ratings#banned'

  get 'emails' => 'bins#emails'

end

app/models/bin.rb
class Bin < ApplicationRecord
  scope :without_deleted, -> { where(deleted_at: nil) }
  scope :with_deleted, -> { where.not(deleted_at: nil) }

  belongs_to :user

  has_many :posts, through: :post_bins
  has_many :post_bins, -> { order(position: :asc) }

  has_attached_file :logo, styles: { medium: "400x400>", thumb: "64x64>" }, default_url: ':placeholder'
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
  validates_attachment_size :logo, :less_than => 1.megabytes

  attr_accessor :posts_attributes

  after_save :set_post_bin_position
  after_save :set_other_bin_positions
  before_save :set_postition_if_nil

  def destroy
    update_attribute(:deleted_at, current_time_from_proper_timezone)
  end

  def set_postition_if_nil
    self.position = Bin.without_deleted.maximum('position') + 1 if position.nil?
  end

  def set_other_bin_positions
    return unless self.position_changed?
    max_position = Bin.without_deleted.maximum('position')

    other_bins = Bin.without_deleted.where.not(id: self.id).sort_by { |bin| bin.position }.to_a
    other_positions = (0..max_position + 1).to_a - [self.position]

    other_bins.each_with_index do |bin, index|
      new_position = other_positions[index]
      bin.update_column(:position, new_position) unless bin.position == new_position
    end

    true
  end

  def posts_attributes=(posts_attributes)
    @post_ids = posts_attributes.map { |post_attribute|
      if post_attribute['title'].present?
        post_attribute.delete('id')
        post = Post.create(post_attribute.merge({bin_id: id}))
        post.id
      elsif post_attribute["id"].present?
        post_attribute["id"]
      end
    }.compact.map(&:to_s)
    self.post_ids = @post_ids
  end

  def set_post_bin_position
    if @post_ids
      post_bins.each do |post_bin|
        post_bin.update_attribute(:position, @post_ids.index(post_bin.post_id.to_s))
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  has_many :participations
  has_many :posts
  has_many :ratings, class_name: 'Rating', foreign_key: 'rater_id'
  has_many :rateeds, class_name: 'Rating', foreign_key: 'ratee_id'

  has_one :bin

  validates :name, :presence => true, :uniqueness => { :case_sensitive => true }
  validates_format_of :name, with: /\A[a-zA-Z0-9_\.]*\z/
  validate :validate_name

  def validate_name
    if User.where(email: name).exists?
      errors.add(:name, :invalid)
    end
  end

  def is_admin?
    name == 'ben' || name == 'napes'
  end

  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.name || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_hash).first
    end
  end
end

app/controllers/bins_controller.rb
class BinsController < ApplicationController
  before_action :set_bin, only: [:show, :edit, :update, :destroy]
  before_action :set_post, only: [:show]
  before_action :redirect_if_non_admin, only: [:index, :emails, :new, :edit, :create, :update, :destroy]

  skip_before_filter :authenticate_user!, only: [:show]

  # GET /bins
  def index
    @hide_footer = true
    @bins = Bin.without_deleted.includes(:posts).order('post_bins.position asc').order(:position)
  end

  # GET /bins/1
  def show
    if not_matching? || browser.device.mobile?
      room = @post.rooms.create(bin: @bin)
    else
      if params['post'].present?
        rooms = @post.rooms.where('rooms.full is false').where('rooms.waiting is true')
        room = rooms.first
      else
        rooms = Room.where('rooms.full is false').where('rooms.waiting is true')
        room = rooms.first
      end

      room = @post.rooms.create(bin: @bin) if room.blank?
    end

    redirect_to room_path(room)
  end

  # GET /bins/new
  def new
    @hide_footer = true
    @bin = Bin.new
    @posts = []
  end

  # GET /bins/1/edit
  def edit
    @hide_footer = true
    @posts = Post.without_deleted.where(bin_id: @bin.id).order(:title)
  end

  # POST /bins
  def create
    @bin = Bin.new(bin_params)

    if @bin.save
      redirect_to action: :index, notice: 'Bin was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bins/1
  def update
    if @bin.update(bin_params)
      redirect_to action: :index, notice: 'Bin was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bins/1
  def destroy
    @bin.destroy
    redirect_to bins_url, notice: 'Bin was successfully destroyed.'
  end

  def emails
    @users = User.all.order(:created_at)
    render :emails
  end

  private

  def not_matching?
    current_user && !current_user.matching?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_bin
    @bin = Bin.find(params[:id])
  end

  def set_post
    if params['post'].present?
      @post = @bin.posts.where(id: params['post']).first

      if @post.nil?
        @post = Post.where(id: params['post']).first
        @bin.posts << @post unless @post.nil?
      end
    end

    @post = @bin.posts.order('post_bins.position asc').first if @post.nil?
  end

  # Only allow a trusted parameter "white list" through.
  def bin_params
    @params ||= begin
      request_params = params.require(:bin).permit(:title, :abbreviation, :description, :position, :logo, :post_ids => (0..50).to_a.map(&:to_s), :posts => [:title, :link, :duration, :text_content] )
      post_ids = request_params['post_ids'].values
      request_params.delete('post_ids')
      posts = request_params['posts'].values
      request_params.delete('posts')

      posts.each_with_index { |post, index| post['id'] = post_ids[index] }
      request_params['posts_attributes'] = posts
      request_params
    end
  end

  def bad_rating?(user_id)
    false
    #return true if current_user.ratings.where('ratee_id = ?', user_id).where('value <= 2').any?
    #return true if current_user.rateeds.where('rater_id = ?', user_id).where('value <= 2').any?
  end

  def just_chat?(user_id)
    (current_user.participations.pluck(:room_id).last(3) & User.find(user_id).participations.pluck(:room_id).last(3)).present?
  end
end

app/helpers/bins_helper.rb
module BinsHelper
end

app/views/bins/_form.html.erb
<%= form_for(bin) do |f| %>
  <% if bin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bin.errors.count, "error") %> prohibited this bin from being saved:</h2>

      <ul>
      <% bin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :abbreviation %><br>
    <%= f.text_field :abbreviation %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="form-group">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>

  <div class="form-group">
    <%= image_tag bin.logo.url(:thumb) %>
    <%= f.file_field :logo %>
  </div>

  <div class="bin-forms">
    <% (0..50).each do |i| %>
      <div class="bin-form">
        <p><%= i + 1 %></p>
        <%= f.collection_select(:post_ids, @posts, :id, :id_with_title, { include_blank: 'None', selected: @bin.posts.order('post_bins.position asc')[i].try(:id) }, { name: "bin[post_ids][#{i}]" }) %>
        <p> Or create a new post</p>
        <%= f.fields_for "posts[#{i}]" do |post| %>
          <div class="fields">
            <div class="field new-post-field new-post-title">
              <%= post.text_field :title, placeholder: 'Title' %>
            </div>
            <div class="field new-post-field">
              <%= post.text_field :link, placeholder: 'Link (optional)' %>
            </div>
            <div class="field new-post-field">
              <%= post.number_field :duration, placeholder: 'Time until skip to next post' %>
            </div>
          </div>
          <div class="new-post-textarea">
            <%= post.text_area :text_content, placeholder: 'Text (optional)' %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bins/edit.html.erb
<h1>Editing Bin</h1>

<%= render 'form', bin: @bin %>

<%= link_to 'Show', @bin %> |
<%= link_to 'Back', bins_path %>

app/views/bins/emails.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>email</th>
      <th>created_at</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bins</h1>

<table>
  <thead>
    <tr>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @bins.each do |bin| %>
      <tr>
        <td><%= image_tag bin.logo.url(:thumb), style: 'max-height:64px;max-width:64px;' %></td>
        <td><%= bin.title %></td>
        <td><%= bin.abbreviation %></td>
        <td><%= bin.position %></td>
        <td>
          <ol>
            <% bin.posts.each do |post| %>
              <li><%= post.title %> - <%= link_to 'Link', bin_path(bin, post: post.id) %></li>
            <% end %>
          </ol>
        </td>
        <td><%= bin.description %></td>
        <td><%= link_to 'Edit', edit_bin_path(bin) %></td>
        <td><%= link_to 'Destroy', bin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bin', new_bin_path %>

app/views/bins/new.html.erb
<h1>New Bin</h1>

<%= render 'form', bin: @bin %>

<%= link_to 'Back', bins_path %>

app/views/bins/show.html.erb
<p id="notice"><%= notice %></p>

<ol>
  <% @bin.posts.each do |post| %>
    <li><%= post.title %></li>
  <% end %>
</ol>

<%= link_to 'Edit', edit_bin_path(@bin) %> |
<%= link_to 'Back', bins_path %>